# Main project settings
verbose = true

port = "COM3"

blacklist = ["steamwebhelper", "wallpaper64", "SteelSeriesMoments", "SpotifyWidgetProvider", "GameBar", "DiscordHookHelper"]

# Automatically select newly opened applications
select_new_app = true

# How many percentage points should the volume be adjusted per click
volume_scroll_size = 5

# Reverse the effect of spinning a knob
invert_volume = false
invert_navigation = false