# This default config file was created automatially

# Grebe Configuration

# Name of serial port to which the microcontroller is connected
port = "COM3"

# Add the name of any process you wish to be hidden
blacklist = ["steamwebhelper", "SpotifyWidgetProvider", "GameBar", "DiscordHookHelper"]

# Aliases allow displayed names of applications to differ from the name provided by Windows
# To use a prefered name add to this list in the form ["default name", "prefered name"]
aliases = [
	["chrome", "Google Chrome"],
	["firefox", "Firefox"],
]

# Automatically select newly opened applications
select_new_app = true

# How many percentage points should the volume be adjusted per click
volume_scroll_size = 5

# Reverse the effect of spinning a knob
invert_volume = false
invert_navigation = false

# Enable to log additional information
# Logs can be found at grebe.log
verbose = false

# Create a shortcut in \Start Menu\Programs
# This is necessary for notifications to appear
add_to_start = true

[notifications]

# Send a notification the first time the microcontroller is connected
on_first_connect = true

# Send a notification when the microcontroller is reconnected after a disconnect
on_reconnect = true

# Send a notification when the microcontroller is disconnected
on_disconnect = true

# When true notifications show on screen but make no noise
silent = false

# Number of seconds until notifications expire
expiration = 15
